version: '3'
services:
  nginx-gen: 
    container_name: nginx-gen
    image: jwilder/nginx-proxy
    restart: always
    ports: 
    - 80:80
    - 443:443
    volumes: 
    - /var/run/docker.sock:/tmp/docker.sock

  app1: 
    restart: always
    build: .
    working_dir: /app
    volumes:
      - ./build/libs:/app
    expose:
      - "8080"
    environment: 
      - VIRTUAL_HOST=app.*
    entrypoint: java
    command: -jar sample-web.jar
    
  app2:
    restart: always
    build: .
    working_dir: /app
    volumes:
      - ./build/libs:/app
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=app.*
    entrypoint: java
    command: -jar sample-web.jar --app.version=2.0

  gradle:
    build:
      context: .
      dockerfile: ./Dockerfile-gradle
    